<?php

namespace Web\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DateClickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateClickRepository extends EntityRepository
{
}
