parameters:
#    web_main.example.class: Web\MainBundle\Example

services:
#    web_main.example:
#        class: %web_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
